### ISSUE TITLE
How to code using JPFITS

### ISSUE THREAD

**Issue by SteveRowl** [user29A/JPFITS#4]
Could you give me a line of code in C# to open a simple 2D mono FITS image (on disc) using the JPFITS library, as I am having difficulty.

Regards

Steve

**Comment by user29A** [comment]
Hi Steve,

string fitsimgstr = "c:\\somedirectory\\afitsfile.fits";//the full file name
int[] range = new int[4]{-1, 0, 0, 0};//the range of the image to load; -1 as the first element indicate full-frame read
bool popheader = true;//populate the header
bool popdata = true;//populate the data
bool dostats = true;//compute image statistics on load
bool dopar = false;//(dont) populate buffers in parallel

FITSImage fitsimgobj = FITSImage(fitsimgstr , range , popheader , popdata , dostats, dopar);

Hope that helps!

Joe

**Comment by SteveRowl** [comment]
Hi Joe:

That certainly helps but I cannot seem to get a basic property such as the Width of an image.
I have tried to access the JPFITS.FITSHeader.

Could you show me how? Thanks.

By the way, if I could ask, what has motivated you to create the JPFITS library?

Regards

Steve

**Comment by user29A** [comment]
Hi Steve,

Based on the code above, you would go:

int width = fitsimgobj.Width

to get the width of the image.

I created the FITS library because there was no good Windows-based object-oriented interface for the FITS data standard. It is used for data reduction and image analysis for my work in astrophysics, etc. It is implemented in CCDLAB:

https://github.com/user29A/CCDLAB

This is a Windows app for data analysis and viewing of FITS images. If you would like to install it on Windows, please see its release page:

https://github.com/user29A/CCDLAB/releases

Cheers!

Joe

**Comment by SteveRowl** [comment]
Hi Joe

Thanks for this. Intellisence was not working in my VS 2019 and as it was late, I stopped. I removed the .suo file from my VS 2019 and restarted the project and Intellisence for JPFITS is working.

I will install CCDLAB when I get a chance.

Regards

Steve
