### ISSUE TITLE
How to Display a JPBitMap.ArrayToBmp

### ISSUE THREAD

**Issue by SteveRowl** [user29A/JPFITS#5]
Hi Joe

Thanks for your continued help.

A friend and I are working to rewrite a popular but old Win astronomy app (VB6) into VB.net. More history to follow.

Dim fitsimgstr As String = "E:\AIP General\wetransfer_small-test-images_2021-09-12_0626\TestImages_Classic\Lena.fts" ';//the full file name
Dim DImCLim() As Double = {0.05, 0.95}   'The image contrast limits. A 2-element array which clips the low (element 1) and high (element 2) values when forming the bitmap.
Dim fitsimgArray(,) As Double

PictureBox1.Image = JPBitMap.ArrayToBmp(fitsimgArray, 0, 0, False, DImCLim, 256, 256, `False)`

where PictureBox1 is a Microsoft PictureBox on a Form.

Image attached.

I get a blank PictureBox.

My question is:
Are these reasonable values for: DImCLim() As Double = {0.05, 0.95}?

Regards

Steve
[Lena.zip](https://github.com/user29A/JPFITS/files/7776770/Lena.zip)

**Comment by user29A** [comment]
Hi Steve,

If you are looking for a good Windows astronomy and FITS display/processor app, I highly suggest to take a look at CCDLAB:

https://github.com/user29A/CCDLAB/releases/download/2021.12.09/CCDLAB.Setup.msi

The image contrast limits are with respect to the FITS image values themselves. A typical good setting is 

DImCLim[0] = fitsimg.mean - 0.5 * fitsimg.stdv;
DImCLim[1] = fitsimg.mean + 5 * fitsimg.stdv;

The function JPBitMap.ArrayToBmp returns a bitmap.

I don't think that PictureBox1.Image = JPBitMap.ArrayToBmp(...) will work. What I do in CCDLAB is:

BITMAPIMG = JPBitMap.ArrayToBmp(...);//first set the BITMAPIMG which is a global variable

Then call PictureBox1.Refresh();

Then in the PictureBox1 Paint method you must have coded:

e.Graphics.InterpolationMode = System.Drawing.Drawing2D.InterpolationMode.NearestNeighbor;
e.Graphics.PixelOffsetMode = System.Drawing.Drawing2D.PixelOffsetMode.Half;
e.Graphics.DrawImage(BITMAPIMG , new Rectangle(0, 0, PictureBox1.Size.Width, PictureBox1.Size.Height));

But again, I highly recommend instead of re-building a Windows app, to now use CCDLAB which already does everything which would ever be needed:

https://github.com/user29A/CCDLAB/wiki

Please take a look at it, and let me know if it satisfies what you need a FITS view/processor to do. I would be happy to work with you on developing a good Windows app for astronomy, etc. CCDLAB already does a lot of things, etc.

Cheers,

Joe

**Comment by user29A** [comment]
Hi again Steve,

You can see a few videos on the CCDLAB YouTube channel:

[CCDLAB](https://www.youtube.com/channel/UCy0BActhCRPM4KZYzCj5vhg)

The videos up are mostly for its use with UVIT data reduction, but the videos demonstrate the basic display and interface, etc.

If you would like to work together to develop features in CCDLAB which you like from other apps, please let me know. CCDLAB is already highly developed so that gets thing much further ahead.

Cheers,

Joe

**Comment by SteveRowl** [comment]
Hi Joe

Thanks. I have installed CCDLAB and referred it to my colleague.

I will get back to you in a week or so when he has reviewed CCDLAB.

Regards

Steve

**Comment by user29A** [comment]
Hi Steve,

If either you or your colleague have questions about CCDLAB, please feel free to email me at:

joepostma@live.ca

I would be happy to discuss with you.

Regards,

Joe

**Comment by SteveRowl** [comment]
Hi Joe

Many thanks

Regards

Steve

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
